### ISSUE TITLE
Reproducibility issue when upgrading from 0.6.0 to 0.6.2

### ISSUE THREAD

**Issue by Haoyu-UT** [tensorforce/tensorforce#740]
Hi, I have been using your framework for quite a long time, and thank you for your great work.
The training process could be reproduced with tensorforce 0.6.0, but not with the latest 0.6.2. It's a very basic training loop, please check the code below.
Also, there is another minor issue, that if I set the 'optimizer' parameter in Agent.create method, it will trigger an error.
```
  File "h:\Work\elegans\SYNC\elegans-rl\reinforcement_learning\rl_DQN_tensorforce.py", line 82, in <module>
    config={'seed': SEED}
  File "C:\Users\haoyu\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorforce\agents\agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "C:\Users\haoyu\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorforce\agents\agent.py", line 98, in create
    agent = agent(**kwargs)
  File "C:\Users\haoyu\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorforce\agents\double_dqn.py", line 219, in __init__
    saver=saver, summarizer=summarizer, **kwargs
TypeError: __init__() got multiple values for keyword argument 'optimizer'
```
```python
env = Environment.create(environment='gym', level='Elegans-v0', max_episode_timesteps=1000, arena_size=400,
                        reward_func_name='goto', use_double_step_state=True)
network_spec = [dict(type='dense', size=64, activation='leaky-relu'),
                dict(type='dense', size=128, activation='tanh'),
                dict(type='dense', size=64, activation='leaky-relu')]
agent_spec = 'double_dqn'
memory = 4096; batch_size = 2048; lr = 5e-4; freq = 1024
if os.path.exists(PATH_TO_MODEL+'agent.json'):
    agent = Agent.load(directory=PATH_TO_MODEL, filename='agent')
else:
    agent = Agent.create(
        agent=agent_spec,
        states=env.states(),
        actions=env.actions(),
        memory=memory,
        batch_size=batch_size,
        exploration=0.05,
        # optimizer=dict(
        #     optimizer='radam',
        #     learning_rate=dict(type='exponential', unit='episodes', num_steps=20, initial_value=lr, decay_rate=0.8)),
        learning_rate=dict(type='exponential', unit='episodes', num_steps=50, initial_value=lr, decay_rate=0.8),
        discount=1.,
        update_frequency=freq,
        network=network_spec,
        config={'seed': SEED}
    )

reward_his = deque([])
angle_his = deque([])
action_his = deque([])
for episode in range(START_EPISODE+1, END_EPISODE+1):
    timestep = 1
    while timestep < MAX_TIMESTEP+1:
        if timestep == 1:
            rewards = []
            states = []
            actions = []
            state = env.reset()
            # agent.reset()
        # Get action
        action = agent.act(state)
        # Execute action in the environment
        state, is_terminal, reward = env.execute(action)
        rewards.append(reward)
        states.append(state)
        actions.append(action)
        timestep += 1
        agent.observe(reward=reward, terminal=bool(is_terminal))
        # Pass observation to the agent
        if is_terminal:
            agent.update()
            print('Finished episode {ep} after {ts} timesteps (reward: {reward})'.format(
                ep=episode, ts=timestep, reward=np.sum(rewards)))
            reward_his.append(np.sum(rewards))
            angle_his.extend([state[3]*6.3-3.15 for state in states])
            action_his.extend(actions)
            break
    if episode%100 == 0:
        agent.save(directory=PATH_TO_MODEL, append='episodes')
```

**Comment by AlexKuhnle** [comment]
Hey @Haoyu-UT,

Thanks, good to hear the framework has been working well for you.

First, there is no `optimizer` argument for `double_dqn`, only the `learning_rate` argument. `double_dqn` is predefined to use the Adam optimizer. One may argue that the optimizer argument should be public, and I'm happy to add that option.

Second, what exactly is going wrong with this code snippet -- can you post the stacktrace? My guess would be that it's the `agent.update()` call? Regarding this `update()` call: If you use `act()` and `observe()`, Tensorforce agents automatically update periodically based on the `batch_size` (and `update_frequency`) you have configured, so there's no need to explicitly call `agent.update()` (this will trigger an update *in addition to* the updates which are triggered automatically). And another little detail: Unclear from the code what you're using the `states`, `actions`, `rewards` lists for, but you're appending the "next state" in `states.append(state)` (since it's the state returned by `env.execute(action)`) -- should this not be before `env.execute()`?

**Comment by Haoyu-UT** [comment]
Hi @AlexKuhnle ,
Thank you very much for your advice, I have never noticed those bugs inside my program before.

However I'm sorry that I did not express my problem clearly. The problem is that I was able to obtain the same reward at each timestep and the same trained model every time I run my program (which means the seed worked correctly), but with 0.6.2 the reward at each timestep varies between program executions.

I fixed the bugs mentioned before, and modified the agent config to better reproduce this issue.
```python
memory = 1024; batch_size = 256; lr = 5e-4; freq = 64
agent = Agent.create(
    agent=agent_spec,
    states=env.states(),
    actions=env.actions(),
    memory=memory,
    batch_size=batch_size,
    exploration=0.05,
    # learning_rate=dict(type='exponential', unit='episodes', num_steps=50, initial_value=lr, decay_rate=0.8),
    learning_rate=lr,
    # discount=1.,
    discount=0.95,
    update_frequency=freq,
    network=network_spec,
    config={'seed': SEED}
    )
```

part of the program output with 0.6.0 (which always keeps the same whenever I execute it.)
```
Finished episode 1 after 1001 timesteps (reward: 10.342600380008264)
Finished episode 2 after 593 timesteps (reward: -337.20679090745)
Finished episode 3 after 252 timesteps (reward: -359.16948464934137)
Finished episode 4 after 1001 timesteps (reward: -132.7118980386328)
Finished episode 5 after 111 timesteps (reward: 189.47344014317935)
Finished episode 6 after 1001 timesteps (reward: -353.55977596339494)
Finished episode 7 after 660 timesteps (reward: -249.02671841748432)
Finished episode 8 after 438 timesteps (reward: -358.6042179244528)
Finished episode 9 after 648 timesteps (reward: -250.46063303277754)
Finished episode 10 after 261 timesteps (reward: -327.7099920387616)
Finished episode 11 after 372 timesteps (reward: 163.0576229744213)
Finished episode 12 after 232 timesteps (reward: -300.9350362384141)
Finished episode 13 after 1001 timesteps (reward: 23.166908465179972)
Finished episode 14 after 1001 timesteps (reward: 43.7776086011605)
Finished episode 15 after 1001 timesteps (reward: -189.54167185722366)
```
part of the program output with 0.6.2 (which varies every time.)
first execution
```
Finished episode 1 after 778 timesteps (reward: -359.31081440257566)
Finished episode 2 after 930 timesteps (reward: -256.4714103126735)
Finished episode 3 after 556 timesteps (reward: -317.29518337462036)
Finished episode 4 after 884 timesteps (reward: -322.0151693549766)
Finished episode 5 after 242 timesteps (reward: -383.9278988121554)
Finished episode 6 after 290 timesteps (reward: -302.3108189658408)
Finished episode 7 after 463 timesteps (reward: -357.50005267774816)
Finished episode 8 after 1001 timesteps (reward: -193.9613251032003)
Finished episode 9 after 1001 timesteps (reward: -145.50727522549104)
Finished episode 10 after 1001 timesteps (reward: 3.7822493170099847)
Finished episode 11 after 522 timesteps (reward: -302.7540699187073)
Finished episode 12 after 997 timesteps (reward: -342.18360923566206)
Finished episode 13 after 203 timesteps (reward: -374.21668333956757)
Finished episode 14 after 1001 timesteps (reward: -26.968713746078663)
Finished episode 15 after 511 timesteps (reward: -332.31983234330863)
```
second execution
```
Finished episode 1 after 778 timesteps (reward: -359.31081440257566)
Finished episode 2 after 930 timesteps (reward: -256.4714103126735)
Finished episode 3 after 556 timesteps (reward: -317.29518337462036)
Finished episode 4 after 884 timesteps (reward: -322.0151693549766)
Finished episode 5 after 242 timesteps (reward: -383.9278988121554)
Finished episode 6 after 290 timesteps (reward: -302.3108189658408)
Finished episode 7 after 463 timesteps (reward: -357.50005267774816)
Finished episode 8 after 1001 timesteps (reward: -193.9613251032003)
Finished episode 9 after 1001 timesteps (reward: -145.50727522549104)
Finished episode 10 after 1001 timesteps (reward: 3.7822493170099847)
Finished episode 11 after 522 timesteps (reward: -302.7540699187073)
Finished episode 12 after 934 timesteps (reward: -387.74911837939703)
Finished episode 13 after 215 timesteps (reward: -253.6855635683663)
Finished episode 14 after 1001 timesteps (reward: -220.04034315134027)
Finished episode 15 after 648 timesteps (reward: -345.8497691505353)
```

**Comment by AlexKuhnle** [comment]
Weird, particularly since it happens only at episode 12, so both the environment and the initial agent updates are perfectly aligned, but then "suddenly" something diverges. I will need to have a look at the changes between 0.6.0 and 0.6.2 to hopefully spot what might be causing this issue.

**Comment by AlexKuhnle** [comment]
Re-open if problem still exists, and ideally provide a script to reproduce the behavior on CartPole or similar.
